#!/usr/bin/env bash
# script transfers a file to a server
# check parameters

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi


file_path=$1
ip=$2
username=$3
sshkey_path=$4

# transfer to remote server
scp -o StrictHostKeyChecking=no -i "$sshkey_path" "$file_path" "$username@$ip":~/
