#!/usr/bin/env bash
# set up a nginx server on a remote server
# update apt cache
sudo apt update

# Install nginx package
sudo apt install -y nginx

# set port number
PORT=80

# replace the default server configuration file with our own
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

sudo cat << EOF > /etc/nginx/sites-available/default
server {
    listen $PORT default_server;
    listen [::]:$PORT default_server;
    root /var/www/html;
    index index.html index.htm;
    server_name localhost;
    location / {
	return 200 'Hello World!\n';
	}
}
EOF

# restart nginx
sudo service nginx restart
