#!/usr/bin/env bash
# sets a redirection in the location /redirect_me
# Install nginx server
sudo apt update
sudo apt install -y nginx

# Set up redirection
sudo sed -i'.bak2' '/server_name localhost;/a \    location \/redirect_me {\n        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart
