#!/usr/bin/env bash
# sets up a redirect
# set up a redirection in the location /redirect_me
REDIRECT_CODE="return 301;"

# append the location block for /redirect_me to the nginx configuration file
sudo sed -i '/server_name localhost;/a \    location /redirect_me {\n        '"$REDIRECT_CODE"'\n    }' /etc/nginx/sites-available/default

# restart nginx
sudo service nginx restart

