#!/usr/bin/env bash
#script configures two servers with custom HTTP response headers

sudo sed -i "/http {/a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
