#!/usr/bin/env bash
#script configures two servers with custom HTTP response headers
sudo apt update && sudo apt upgrade
sudo apt install -y  nginx
sudo sed -i "/http {/a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
