#!/usr/bin/env bash
# installing a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend ndegz-front
        bind *:80
        mode http
        default_backend ndegz-back

backend ndegz-back
        balance roundrobin
        server 156072-web-01 54.210.51.207:80 check
        server 156072-web-02 100.26.238.247:80 check
"
echo "$server_config" |sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
