#!/usr/bin/env bash
# The bash script displays the contents of the file /etc/passwd
while read -r line; do
  username=$(echo "$line" | cut -d: -f1)
  userid=$(echo "$line" | cut -d: -f3)
  homedir=$(echo "$line" | cut -d: -f6)
  echo "$username:$userid:$homedir"
done < /etc/passwd

