#!/usr/bin/env bash
#run nginx as nginx user

chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\8080 /' /etc/nginx/sites-enabled/default

su nginx -s /bin/bash - c 'service nginx restart'
